import React, { useState, useMemo } from 'react';
import { Member, CheckIn, Transaction, TierConfig, getTier } from '../lib/types';
import { IC, Badge, Av, ExpBar, Field, InfoRow, TxAmt, fD, fT } from '../components/ui';

export function MembersPage({members,onView,onAdd,tiers}:{members:Member[];onView:(id:string)=>void;onAdd:()=>void;tiers:TierConfig[]}) {
  const [q,setQ]=useState('');const [ft,setFt]=useState('all');const [sort,setSort]=useState<'name'|'exp'|'koin'|'joined'>('name');
  const list=useMemo(()=>{let l=[...members];if(q){const s=q.toLowerCase();l=l.filter(m=>m.full_name.toLowerCase().includes(s)||m.phone?.includes(s)||m.email.toLowerCase().includes(s));}if(ft!=='all')l=l.filter(m=>getTier(m.total_exp,tiers).name===ft);l.sort((a,b)=>sort==='name'?a.full_name.localeCompare(b.full_name):sort==='exp'?b.total_exp-a.total_exp:sort==='koin'?b.koin_balance-a.koin_balance:+new Date(b.joined_at)-+new Date(a.joined_at));return l;},[members,q,ft,sort,tiers]);
  return(<div className="space-y-4">
    <div className="flex items-center justify-between"><h1 className="font-mono text-xl font-bold" style={{color:'#231F20'}}>Members</h1><button onClick={onAdd} className="flex items-center gap-1.5 px-3 py-2 rounded font-mono text-[10px] uppercase tracking-widest font-bold text-white hover:brightness-110" style={{background:'#003820'}}>{IC.add} Tambah</button></div>
    <div className="relative"><div className="absolute left-3 top-1/2 -translate-y-1/2" style={{color:'#231F2066'}}>{IC.search}</div><input value={q} onChange={e=>setQ(e.target.value)} className="w-full pl-10 pr-4 py-2.5 rounded-lg border font-mono text-sm focus:outline-none focus:border-[#C39A4B]" style={{borderColor:'#231F2015',color:'#231F20'}} placeholder="Cari member..."/></div>
    <div className="flex gap-1.5 overflow-x-auto pb-1"><button onClick={()=>setFt('all')} className="shrink-0 font-mono text-[10px] uppercase tracking-widest px-3 py-1.5 rounded-full" style={ft==='all'?{background:'#003820',color:'#E0DBBC'}:{border:'1px solid #231F2020',color:'#231F2066'}}>Semua</button>{tiers.map(t=><button key={t.id} onClick={()=>setFt(t.name)} className="shrink-0 font-mono text-[10px] uppercase tracking-widest px-3 py-1.5 rounded-full" style={ft===t.name?{background:t.bg,color:t.badgeText}:{border:'1px solid #231F2020',color:'#231F2066'}}>{t.name}</button>)}</div>
    <div className="flex gap-1.5">{([['name','Nama'],['exp','EXP'],['koin','Koin'],['joined','Terbaru']] as const).map(([k,l])=><button key={k} onClick={()=>setSort(k as any)} className="font-mono text-[9px] uppercase tracking-widest px-2 py-1 rounded" style={sort===k?{background:'#003820',color:'#E0DBBC'}:{color:'#231F2066'}}>{l}</button>)}</div>
    <div className="space-y-2">{list.map(m=>{const tier=getTier(m.total_exp,tiers);return <div key={m.id} onClick={()=>onView(m.id)} className="flex items-center justify-between p-3 rounded-lg border cursor-pointer hover:border-[#C39A4B55] active:scale-[0.99]" style={{borderColor:'#231F2010'}}><div className="flex items-center gap-3 min-w-0"><Av name={m.full_name} size={40} tier={tier}/><div className="min-w-0"><div className="font-mono text-sm font-medium flex items-center gap-2" style={{color:'#231F20'}}><span className="truncate">{m.full_name}</span>{!m.is_active&&<span className="shrink-0 text-[9px] px-1.5 py-0.5 rounded bg-red-100 text-red-600">Inactive</span>}</div><Badge tier={tier}/></div></div><div className="text-right shrink-0 ml-2"><div className="font-mono text-xs font-bold" style={{color:'#231F20'}}>{m.total_exp}<span className="text-[9px]" style={{color:'#231F2088'}}> EXP</span></div><div className="font-mono text-[10px] font-medium" style={{color:'#C39A4B'}}>{m.koin_balance} Koin</div></div></div>;})}<p className="font-mono text-[10px] text-center pt-2" style={{color:'#231F2088'}}>{list.length} member</p></div>
  </div>);
}

export function MemberDetailPage({member,transactions,checkins,onBack,onEdit,tiers}:{member:Member;transactions:Transaction[];checkins:CheckIn[];onBack:()=>void;onEdit:()=>void;tiers:TierConfig[]}) {
  const tier=getTier(member.total_exp,tiers);const mTx=transactions.filter(t=>t.member_id===member.id).sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at));const mCi=checkins.filter(c=>c.member_id===member.id);const [tab,setTab]=useState<'info'|'history'|'benefits'>('info');
  const isTop=tier.id==='tier4';const cBg=isTop?tier.bg:`${tier.text}08`;const cTx=isTop?'#E0DBBC':'#231F20';const cM=isTop?'#E0DBBC88':'#231F2088';
  return(<div className="space-y-5">
    <div className="flex items-center justify-between"><button onClick={onBack} style={{color:'#231F2088'}}>{IC.back}</button><button onClick={onEdit} className="flex items-center gap-1 font-mono text-[10px] uppercase tracking-widest font-bold" style={{color:'#C39A4B'}}>{IC.edit} Edit</button></div>
    <div className="text-center p-5 rounded-lg border-2" style={{borderColor:tier.text,background:cBg}}>
      <div className="flex justify-center"><Av name={member.full_name} size={64} tier={tier}/></div>
      <div className="mt-3 font-mono text-lg font-bold" style={{color:cTx}}>{member.full_name}</div><div className="mt-1.5"><Badge tier={tier} size="md"/></div>
      <div className="mt-3 flex justify-center gap-6"><div className="text-center"><div className="font-mono text-lg font-bold" style={{color:cTx}}>{member.total_exp}</div><div className="font-mono text-[9px] uppercase" style={{color:cM}}>EXP</div></div><div className="w-px" style={{background:isTop?'#E0DBBC33':'#231F2020'}}/><div className="text-center"><div className="font-mono text-lg font-bold" style={{color:'#C39A4B'}}>{member.koin_balance}</div><div className="font-mono text-[9px] uppercase" style={{color:cM}}>Koin</div></div></div>
      <div className="mt-3 px-6"><ExpBar exp={member.total_exp} tier={tier}/></div>
    </div>
    <div className="flex border-b" style={{borderColor:'#231F2010'}}>{(['info','history','benefits'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`flex-1 font-mono text-[10px] uppercase tracking-widest py-2.5 border-b-2 ${tab===t?'font-bold':''}`} style={tab===t?{borderColor:'#003820',color:'#003820'}:{borderColor:'transparent',color:'#231F2066'}}>{t==='info'?'Info':t==='history'?'History':'Benefits'}</button>)}</div>
    {tab==='info'&&<div><InfoRow label="Email" value={member.email}/><InfoRow label="Phone" value={member.phone||'—'}/><InfoRow label="Tanggal Lahir" value={member.date_of_birth?fD(member.date_of_birth):'—'}/><InfoRow label="Member Sejak" value={fD(member.joined_at)}/><InfoRow label="Status" value={member.is_active?'Active':'Inactive'}/><InfoRow label="Total Check-in" value={String(mCi.length)}/></div>}
    {tab==='history'&&<div className="space-y-2">{mTx.length===0?<p className="font-mono text-xs text-center py-6" style={{color:'#231F2088'}}>Belum ada</p>:mTx.map(tx=>(<div key={tx.id} className="p-3 rounded-lg border" style={{borderColor:'#231F2010'}}><div className="flex items-center justify-between"><div className="font-mono text-xs font-medium truncate" style={{color:'#231F20'}}>{tx.description}</div><div className="shrink-0 ml-2"><TxAmt exp={tx.exp_amount} koin={tx.koin_amount} compact/></div></div><div className="flex justify-between mt-1"><div className="font-mono text-[9px] flex items-center gap-1" style={{color:'#231F2066'}}>{IC.staff} {tx.staff_name}</div><div className="font-mono text-[9px]" style={{color:'#231F2066'}}>{fD(tx.created_at)} · {fT(tx.created_at)}</div></div></div>))}</div>}
    {tab==='benefits'&&<div className="space-y-2">{tier.benefits.map((b,i)=><div key={i} className="flex items-center gap-3 p-3 rounded-lg border" style={{borderColor:'#231F2010'}}><div className="w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-bold text-white shrink-0" style={{background:tier.text}}>✓</div><span className="font-mono text-xs" style={{color:'#231F20'}}>{b}</span></div>)}</div>}
  </div>);
}

export function MemberFormPage({member,onSave,onBack}:{member?:Member;onSave:(d:Partial<Member>)=>void;onBack:()=>void}) {
  const [f,setF]=useState({full_name:member?.full_name||'',email:member?.email||'',phone:member?.phone||'',date_of_birth:member?.date_of_birth||'',is_active:member?.is_active??true});
  const u=(k:string,v:any)=>setF(p=>({...p,[k]:v}));
  return(<div className="space-y-5">
    <div className="flex items-center justify-between"><button onClick={onBack} style={{color:'#231F2088'}}>{IC.back}</button><h1 className="font-mono text-sm font-bold" style={{color:'#231F20'}}>{member?'Edit':'Tambah'} Member</h1><div className="w-5"/></div>
    <div className="space-y-4"><Field label="Nama Lengkap" value={f.full_name} onChange={v=>u('full_name',v)} ph="John Doe"/><Field label="Email" value={f.email} onChange={v=>u('email',v)} type="email" ph="john@mail.com"/><Field label="Phone" value={f.phone} onChange={v=>u('phone',v)} type="tel" ph="08123456789"/><Field label="Tanggal Lahir" value={f.date_of_birth} onChange={v=>u('date_of_birth',v)} type="date"/>
      {member&&<div className="flex items-center justify-between py-3 border-t" style={{borderColor:'#231F2010'}}><span className="font-mono text-[10px] uppercase tracking-widest" style={{color:'#231F2088'}}>Active</span><button onClick={()=>u('is_active',!f.is_active)} className={`w-11 h-6 rounded-full relative ${f.is_active?'bg-green-500':'bg-gray-300'}`}><div className={`absolute top-0.5 w-5 h-5 rounded-full bg-white shadow transition-transform ${f.is_active?'left-[22px]':'left-0.5'}`}/></button></div>}
    </div>
    <button onClick={()=>onSave(f)} className="w-full py-3 rounded-lg font-mono text-sm font-bold uppercase tracking-widest text-white hover:brightness-110 active:scale-[0.98]" style={{background:'#003820'}}>{member?'Simpan':'Tambah'}</button>
  </div>);
}
